{{ if not .Values.drogueIoT }}
kind: Secret
apiVersion: v1
metadata:
  name: mqtt2kafka
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.kafka.brokers: {{ .Values.kafka.bootstrap.servers }}
    com.redhat.bobbycar.camelk.kafka.topic: {{ .Values.kafka.topic.metrics }}
    com.redhat.bobbycar.camelk.kafka.topicZoneChange: {{ .Values.kafka.topic.zonechange }}
    com.redhat.bobbycar.camelk.mqtt.brokerUrl: tcp://bobbycar-amq-mqtt-all-0-svc:61616
    com.redhat.bobbycar.camelk.mqtt.topic: {{ .Values.mqtt.topic.mqttMetricsTopic }}
    com.redhat.bobbycar.camelk.mqtt.topicZoneChange: {{ .Values.mqtt.topic.mqttZoneChangeTopic }}
type: Opaque
{{ end }}