kind: Secret
apiVersion: v1
metadata:
  name: weather-service-secret
data:
  apiKey: {{ .Values.weatherService.owm.api.key | default "not-set" | b64enc }}
  ibmApiKey: {{ .Values.weatherService.ibm.api.key | default "not-set" | b64enc }}
type: Opaque