NAMESPACE=
APP_DOMAIN=
API_DOMAIN=

GOOGLE_API_KEY=
OWM_WEATHER_API_KEY=
IBM_WEATHER_API_KEY=

INSTALL_KNATIVE=true
INSTALL_OPERATORS=true
DELETE_CRD=true

HELM_INFRA_RELEASE_NAME=infra
HELM_APP_RELEASE_NAME=apps
HELM_SERVERLESS_RELEASE_NAME=serverless