{{ if not .Values.drogueIoT }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-bridge
  namespace: {{ .Values.namespace }}
spec:
  host: bobbycar-{{ .Values.namespace }}.{{ .Values.ocpDomain }}
  to:
    kind: Service
    name: bobbycar-bridge-service
    weight: 100
  port:
    targetPort: rest-api
  wildcardPolicy: None
{{ end }}