FROM registry.access.redhat.com/ubi8/nodejs-14

ENV OUTPUT_DIR=www

COPY ./ .

RUN pwd && ls -la

RUN /usr/libexec/s2i/assemble

#COPY ./www/ .
COPY nginx.conf /etc/nginx/nginx.conf

RUN pwd && ls -la

#Run script uses standard ways to run the application
#CMD nginx -g "daemon off;"