FROM registry.access.redhat.com/ubi8/nodejs-14

RUN pwd && ls -la

RUN /usr/libexec/s2i/assemble

RUN pwd && ls -la


#COPY ./www/ .
COPY nginx.conf /etc/nginx/nginx.conf

#Run script uses standard ways to run the application
#CMD nginx -g "daemon off;"