kind: KnativeKafka
apiVersion: operator.serverless.openshift.io/v1alpha1
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  broker:
    enabled: true
    defaultConfig:
      numPartitions: 2
      replicationFactor: 1
      bootstrapServers: 'bobbycar-cluster-kafka-bootstrap.bobbycar.svc.cluster.local:9092'
  source:
    enabled: true
  sink:
    enabled: true  
  channel:
    enabled: true
    bootstrapServers: 'bobbycar-cluster-kafka-bootstrap.bobbycar.svc.cluster.local:9092'